* Соединение таблиц

Соединение двух и более таблиц, можно рассматривать как процесс сравнение данных в 
указаных столбцах и формирование новой таблицы из строк исходных таблиц, которые дают
положительный результат.

Наиболее часто встречается соединение с равенством.

При выполнении соединения сначала образуется декартово произведение, то есть
образование всех возможных комбинаций строк этих таблиц друг с другом.

Декартово произведение не содержит никакой полезной информации -> соединение должно 
включать предложение =WHERE=, которое отбирает связанные между собой строки и указывает как именно
они должны быть связаны.

*** Пример

Найти название всех книг и имена авторов.

#+begin_src sql
SELECT title.title_name, authors.au_fname, authors.au_lname FROM authors, titles, title_authors
WHERE title_authors.au_id = authors.au_id AND title.title_id = title_authors.title_id
#+end_src

=CROSS JOIN= - декартово произведение, где используются все возможные комбинации строк

=INNER JOIN= - соединяются только те строки, где найдены совпадающие значениея столбца

=LEFT (OUTER) JOIN= - включает в себя все строки из таблицы и строки с совп. из таблицы B, 
для строк, которым ненайдено соответствие в таблице, ставится NULL

=RIGHT (OUTER) JOIN= - обратное соединение предыдущего

=FULL OUTER JOIN= - 

=UNION= - является обратным к INNER JOIN, то есть включет только те строки из таблиц
