* Индекс
Избыточная структура, предназначенная для ускорения поиска

Основное назначение:
  - Увеличение скорости доступа к данным
  - Поддержка уникальности данных
  - Автоматическое упорядочение записей
  - Поиск с помощью индекса
  - Точное значение атрибута
  - Интервал значений атрибута
  - Значение нескольких атрибутов

Способы создания индекса:
  - Автоматическое создание индекса при создании первичного ключа
  - Автоматическое создание индекса при определении ограничения целостности unique
  - Создание индекса с помощью команды create index- Создание индекса
  - CREATE INDEX имя индекса on имя таблицы (столбец)
    
Удаление индекса
  - DROP INDEX имя индекса on имя таблицы
  
Архитектура удаленных БД

За все время существования электронных БД было
реализовано 3 архитектуры:
  * Локальные бД – в этом случае размещается сама БД и ее СУБД.
    Работа с базой организована в однопользовательском режиме.
    На приложение клиента возложено обеспечение достоверности и
    целостности данных, формирование запросов к БД и интерпретация
    полученных ответов.
    
    Достоинство – за счет работы единственного пользователя
    обеспечивается высокая степень безопасности
    
    Недостаток – возможность работы только одного пользователя.

  * Архитектура файл-сервер – в этом случае БД располагается на сетевом сервере,
    а приложение клиента на пользовательском ПК. Кол-во пользователей не более 10-15.
    Каждый пользователь переписывает на свой ПК копию, которая периодически обновляется
    с сервера. Имеется доп. трудность по блокировке записей, которые используются
    другими пользователями. Поэтому в некоторые моменты времени пользователь может
    видеть недостоверные сведения в БД.

    Достоинство - возможность работы нескольких пользователей
    Недостатки – перегрузка сети, сложно обеспечить секретность данных,
    необходимость систематического обновления на всех ПК пользователей, блокировка
    данных

   * Архитектура клиент-сервер – в ее основе лежит распределенная модель вычисления.
    В самом общем случае под клиентом и сервером понимается два взаимодействующих
    процесса Сервер – логический процесс, который обеспечивает некоторый сервис по запросу
    от клиента. Обычно сервер не только выполняет запрос, но и управляет очередностью
    запросов, буфером обмена, а также извещает клиентов о выполнении запроса.
    **Клиент** – процесс, который запрашивает обслуживание от Сервера.
    При данном взаимодействии инициатором диалога является клиент.
    Например, сервером может выступать СУБД, а клиентом – приложение,
    созданное в среде разработки, которое использует данные с сервера.

    Достоинства – резко уменьшается сетевой трафик, единые правила для всех пользователей
    (высокая степень защиты), практически все расчеты производятся на сервере, что увеличивает быстродействие.
