* Подзапросы с квантором EXISTS

# Так как работаю с большим разрешением, в тексте меньше переносов, рекомендую это исправить.
Подзапросы, которым, предшествует ключевое слово EXISTS. 

Особенности:

1. Перед ключевым словом EXISTS не должно быть названий столбцов, констант и других выражений.
2. Подзапрос с квантором существования возращает значения TRUE или FALSE и не возвращает никаких данных из таблицы
3. Список выбора такого подхапоса часто состоит из одной *, так как нет необходимости указывать названия столбцов, так как осуществляется
проверка существования строк.

*** Задание 1

Найти название всех издательств, которые публиковали книги по бизнесу

#+begin_src sql
SELECT PUB_NAME FROM PUBLISHERS WHERE EXISTS(SELECT * FROM TITLES WHERE TITLES.PUB_ID=PUBLISHERS.PUB_ID AND TYPE='BUISNESS'
#+end_src

*** Задание 2

Найти авторов, которые живут в одном городе с издательством

#+begin_src sql
SELECT au_fname, au_lname FROM authors WHERE EXISTS(SELECT * FROM publishers WHERE publishers.city=authors.city)
#+end_src

