* Компонентный подход в программировании
Предполагает построение ПО из отдельных компонентов, то есть
физически отдельно существующих частей ПО, которые взаимодействуют
между собой через стандартные интерфейсы.

**ActiveX Date Object (ADO)** – программный интерфейс для доступа
к данным через приложения.

Провайдер данных – компонент ПО, манипулирующий данными.
Он располагается между потребителем данных и БД. Как правило,
все провайдеры представляют данные в табличном формате.

Функции провайдера:
 - Получение от потребителя запросов на получение/модификацию данных
 - Получение данных из базы
 - Возвращение данных потребителю

** Sqlite

Кроссплатформенное встраевоемое СУБД

Локальная БД
Не имеет выделенного сервера, движлк включается в
приложение в виде библиотеки и предоставляет доступ к базе через API

SQLite хранит всю бд в файле на машине пользователя

Исходный код открыт

SQLite используется:
 1) в музыкальных плеерах
 2) в мобильных телефонах
 3) в браузерах
 4) в Skype
 5) в системе Airbus A350

SQLite очень надежный.

Типы данных:
  - Null
  - Integer
  - Real
  - Text
  - Blob

** Строковое представление даты и времени

Для того, чтобы SQLite правильно работал с датой, строка должна быть в
одном из следующих форматов:

  - YYYY-MM-DD
  - YYYY-MM-DD HH:MM
  - YYYY-MM-DD HH:MM:SS
  - YYYY-MM-DD HH:MM:SS.SSS
  - HH:MM
  - HH:MM:SS
  - HH:MM:SS.SSS

В sqlite3 по умолчанию отключена поддержка внешних ключей,
команда pragma позволяет включить внешние ключи в бд sqlite

pragma foreign_keys=on;

** Check ограничение

Check ограничение даст возможность проверить значение,
введенное в запись. Если условие принимает значение false, то
ограничение нарушено и в таблицу оно не попадет

Пример.

Create table company(
id int primary key not null,
name text not null,
age int not null,
address char(50),
salary real check(salary > 0)
);
